/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AprovalRate: typeof import('./components/AprovalRate.vue')['default']
    BarcodeCombobox: typeof import('./components/BarcodeCombobox.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    CollectForm: typeof import('./components/CollectForm.vue')['default']
    ConfigEmailAddDialog: typeof import('./components/ConfigEmailAddDialog.vue')['default']
    ConfigEmailDeleteDialog: typeof import('./components/ConfigEmailDeleteDialog.vue')['default']
    ConfigEmailEditDialog: typeof import('./components/ConfigEmailEditDialog.vue')['default']
    DepartmentAddDialog: typeof import('./components/DepartmentAddDialog.vue')['default']
    DepartmentDeleteDialog: typeof import('./components/DepartmentDeleteDialog.vue')['default']
    DepartmentEditDialog: typeof import('./components/DepartmentEditDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobtitleAddDialog: typeof import('./components/JobtitleAddDialog.vue')['default']
    JobtitleDeleteDialog: typeof import('./components/JobtitleDeleteDialog.vue')['default']
    JobtitleEditDialog: typeof import('./components/JobtitleEditDialog.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    PartCheck: typeof import('./components/PartCheck.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffAddDialog: typeof import('./components/StaffAddDialog.vue')['default']
    StaffDeleteDialog: typeof import('./components/StaffDeleteDialog.vue')['default']
    StaffEditDialog: typeof import('./components/StaffEditDialog.vue')['default']
    STInputField: typeof import('./components/STInputField.vue')['default']
    StockadjustmentAddDialog: typeof import('./components/StockadjustmentAddDialog.vue')['default']
    StockadjustmentDeleteDialog: typeof import('./components/StockadjustmentDeleteDialog.vue')['default']
    StockadjustmentEditDialog: typeof import('./components/StockadjustmentEditDialog.vue')['default']
    StockinAddDialog: typeof import('./components/StockinAddDialog.vue')['default']
    StockinDeleteDialog: typeof import('./components/StockinDeleteDialog.vue')['default']
    StockinEditDialog: typeof import('./components/StockinEditDialog.vue')['default']
    TMInputField: typeof import('./components/TMInputField.vue')['default']
    TransactionOverview: typeof import('./components/TransactionOverview.vue')['default']
  }
}
