/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/AddPurchase': RouteRecordInfo<'/AddPurchase', '/AddPurchase', Record<never, never>, Record<never, never>>,
    '/Analysis': RouteRecordInfo<'/Analysis', '/Analysis', Record<never, never>, Record<never, never>>,
    '/Analyticcode-Analysis': RouteRecordInfo<'/Analyticcode-Analysis', '/Analyticcode-Analysis', Record<never, never>, Record<never, never>>,
    '/AnalyticReport': RouteRecordInfo<'/AnalyticReport', '/AnalyticReport', Record<never, never>, Record<never, never>>,
    '/Categories': RouteRecordInfo<'/Categories', '/Categories', Record<never, never>, Record<never, never>>,
    '/CollectionReport': RouteRecordInfo<'/CollectionReport', '/CollectionReport', Record<never, never>, Record<never, never>>,
    '/CostEvaluation': RouteRecordInfo<'/CostEvaluation', '/CostEvaluation', Record<never, never>, Record<never, never>>,
    '/Department-Analysis': RouteRecordInfo<'/Department-Analysis', '/Department-Analysis', Record<never, never>, Record<never, never>>,
    '/Departments': RouteRecordInfo<'/Departments', '/Departments', Record<never, never>, Record<never, never>>,
    '/EmailReports': RouteRecordInfo<'/EmailReports', '/EmailReports', Record<never, never>, Record<never, never>>,
    '/EngineerDashboard': RouteRecordInfo<'/EngineerDashboard', '/EngineerDashboard', Record<never, never>, Record<never, never>>,
    '/EngineerProfile': RouteRecordInfo<'/EngineerProfile', '/EngineerProfile', Record<never, never>, Record<never, never>>,
    '/JobTitles': RouteRecordInfo<'/JobTitles', '/JobTitles', Record<never, never>, Record<never, never>>,
    '/Matrix': RouteRecordInfo<'/Matrix', '/Matrix', Record<never, never>, Record<never, never>>,
    '/OrderTypes': RouteRecordInfo<'/OrderTypes', '/OrderTypes', Record<never, never>, Record<never, never>>,
    '/PaymentTerms': RouteRecordInfo<'/PaymentTerms', '/PaymentTerms', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/PurchaseDetails/[purchaseDetails]': RouteRecordInfo<'/PurchaseDetails/[purchaseDetails]', '/PurchaseDetails/:purchaseDetails', { purchaseDetails: ParamValue<true> }, { purchaseDetails: ParamValue<false> }>,
    '/RunningStock': RouteRecordInfo<'/RunningStock', '/RunningStock', Record<never, never>, Record<never, never>>,
    '/ScanCode': RouteRecordInfo<'/ScanCode', '/ScanCode', Record<never, never>, Record<never, never>>,
    '/Staff': RouteRecordInfo<'/Staff', '/Staff', Record<never, never>, Record<never, never>>,
    '/Stock-Chart': RouteRecordInfo<'/Stock-Chart', '/Stock-Chart', Record<never, never>, Record<never, never>>,
    '/StockAdjustment-Registered': RouteRecordInfo<'/StockAdjustment-Registered', '/StockAdjustment-Registered', Record<never, never>, Record<never, never>>,
    '/StockAdjustment-Scan': RouteRecordInfo<'/StockAdjustment-Scan', '/StockAdjustment-Scan', Record<never, never>, Record<never, never>>,
    '/StockIn-Registered': RouteRecordInfo<'/StockIn-Registered', '/StockIn-Registered', Record<never, never>, Record<never, never>>,
    '/StockIn-Scan': RouteRecordInfo<'/StockIn-Scan', '/StockIn-Scan', Record<never, never>, Record<never, never>>,
    '/StockOut-Registered': RouteRecordInfo<'/StockOut-Registered', '/StockOut-Registered', Record<never, never>, Record<never, never>>,
    '/StockOut-Scan': RouteRecordInfo<'/StockOut-Scan', '/StockOut-Scan', Record<never, never>, Record<never, never>>,
    '/SupplierAnalysis': RouteRecordInfo<'/SupplierAnalysis', '/SupplierAnalysis', Record<never, never>, Record<never, never>>,
    '/Suppliers': RouteRecordInfo<'/Suppliers', '/Suppliers', Record<never, never>, Record<never, never>>,
    '/ViewPurchase': RouteRecordInfo<'/ViewPurchase', '/ViewPurchase', Record<never, never>, Record<never, never>>,
  }
}
