/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Departments': RouteRecordInfo<'/Departments', '/Departments', Record<never, never>, Record<never, never>>,
    '/EngineerDashboard': RouteRecordInfo<'/EngineerDashboard', '/EngineerDashboard', Record<never, never>, Record<never, never>>,
    '/JobTitles': RouteRecordInfo<'/JobTitles', '/JobTitles', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/RunningStock': RouteRecordInfo<'/RunningStock', '/RunningStock', Record<never, never>, Record<never, never>>,
    '/Staff': RouteRecordInfo<'/Staff', '/Staff', Record<never, never>, Record<never, never>>,
    '/StockAdjustment-Registered': RouteRecordInfo<'/StockAdjustment-Registered', '/StockAdjustment-Registered', Record<never, never>, Record<never, never>>,
    '/StockAdjustment-Scan': RouteRecordInfo<'/StockAdjustment-Scan', '/StockAdjustment-Scan', Record<never, never>, Record<never, never>>,
    '/StockIn-Registered': RouteRecordInfo<'/StockIn-Registered', '/StockIn-Registered', Record<never, never>, Record<never, never>>,
    '/StockIn-Scan': RouteRecordInfo<'/StockIn-Scan', '/StockIn-Scan', Record<never, never>, Record<never, never>>,
    '/StockOut-Registered': RouteRecordInfo<'/StockOut-Registered', '/StockOut-Registered', Record<never, never>, Record<never, never>>,
    '/StockOut-Scan': RouteRecordInfo<'/StockOut-Scan', '/StockOut-Scan', Record<never, never>, Record<never, never>>,
  }
}
